name: project_template
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.14
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - notebook
  - numpy
  - scipy
  - pandas
  - pytest
  - ruff
  - scikit-learn
  - tqdm
  - pyrefly
  - pre-commit
  - draccus
  - loguru
  - safetensors
  - pip
  - pip:
    - more-itertools

