name: project_template
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.14
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - notebook
  - numpy
  - scipy
  - pandas
  - pytest
  - python-dotenv
  - ruff
  - scikit-learn
  - tqdm
  - pyright
  - draccus
  - loguru
  - safetensors
  - pip
  - pip:
    - more-itertools

